### PR TITLE
Update map.xml

### PR DESCRIPTION
**Pull request by MohammedAttya2**
Update map formatting to be more readable

### CODE REVIEW

**Comment by AlaaAttya** [comment]
Thanks @MohammedAttya2 for contributing can you please update the screenshot file too?

**Review by AlaaAttya — CHANGES_REQUESTED** [review]
@MohammedAttya2 can you please use the same colors and font styles

**Comment by MohammedAttya2** [comment]
I'll update the screenshot after going home.

**Comment by MohammedAttya2** [comment]
I update the image on readme

**Comment by AlaaAttya** [comment]
@MohammedAttya2 it's still in the old colors and fonts

screen shot 2018-05-20 at 9 49 55 am

**Comment by MohammedAttya2** [comment]
I changed the blue color to dark blue
green text to black
red to dark red
make fonts bigger
image with white background

**Comment by AlaaAttya** [comment]
@MohammedAttya2 dude check the last request changes `can you please use the same colors and font styles`

**Pull request closed without merging**
